package com.sakuya.navigation

const val PROFILE_ROUTE = "profile"
const val PROFILE_ME = "profile_me"
const val PROFILE_READING_HISTORY = "profile_reading_history"
const val PROFILE_AVATAR = "profile_avatar"
const val PROFILE_NAME = "profile_name"
const val PROFILE_GENDER = "profile_gender"
const val PROFILE_REGION = "profile_region"
const val PROFILE_PHONE = "profile_phone"
const val PROFILE_ID = "profile_id"
const val PROFILE_POKE = "profile_poke"
const val PROFILE_SIGNATURE = "profile_signature"
const val PROFILE_RINGTONE = "profile_ringtone"
const val PROFILE_EDIT_ROUTE = "profile_edit"
const val PROFILE_PRIVACY_ROUTE = "profile_privacy"
