package com.sakuya.navigation

const val SEARCH_ROUTE = "search"
const val SEARCH_RESULTS_BASE_ROUTE = "search/results"
const val SEARCH_RESULTS_ARG_QUERY = "query"
const val SEARCH_RESULTS_ROUTE = "$SEARCH_RESULTS_BASE_ROUTE?$SEARCH_RESULTS_ARG_QUERY={$SEARCH_RESULTS_ARG_QUERY}"
const val WENKU8_DETAIL_ARG_ID = "novelId"
const val WENKU8_DETAIL_BASE_ROUTE = "wenku8/detail"
const val WENKU8_DETAIL_ROUTE = "$WENKU8_DETAIL_BASE_ROUTE?$WENKU8_DETAIL_ARG_ID={$WENKU8_DETAIL_ARG_ID}"
