package com.sakuya.backend.catalog;
import com.sakuya.backend.common.*; import jakarta.validation.constraints.*; import java.time.ZoneId; import java.time.format.DateTimeFormatter; import java.util.*; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController
public class CatalogController {
 private final BookRepository books; private final UserLibraryRepository library; public CatalogController(BookRepository books,UserLibraryRepository library){this.books=books;this.library=library;}
 @GetMapping("/home/recommendations") ApiResponse<List<ContentItem>> recommendations(Authentication auth){return ApiResponse.ok(items(books.findByCategoryOrderByRatingDesc("recommend"),AuthSupport.userId(auth)));}
 @GetMapping("/home/novels") ApiResponse<List<ContentItem>> novels(Authentication auth){return ApiResponse.ok(items(books.findByCategoryOrderByRatingDesc("novel"),AuthSupport.userId(auth)));}
 @GetMapping("/home/rankings") ApiResponse<List<RankingItem>> rankings(Authentication auth){List<ContentItem> list=items(books.findAll().stream().sorted(Comparator.comparing(Book::getRating).reversed()).limit(20).toList(),AuthSupport.userId(auth));return ApiResponse.ok(java.util.stream.IntStream.range(0,list.size()).mapToObj(i->new RankingItem(i+1,list.get(i))).toList());}
 /**
  * 职责说明：提供已公布的轻小说更新资料。
  * 执行流程：维护端给出小说 ID、公布日期和卷信息 -> 控制器匹配现有书目 -> 客户端按日期分组展示时间表。
  */
 @GetMapping("/novels/releases") ApiResponse<List<NovelReleaseItem>> releases(Authentication auth){UUID user=AuthSupport.userId(auth);Map<String,Book> byId=books.findAll().stream().collect(java.util.stream.Collectors.toMap(Book::getId,b->b));return ApiResponse.ok(PUBLISHED_RELEASES.stream().map(r->{Book b=byId.get(r.bookId());return b==null?null:new NovelReleaseItem(item(b,user),r.releaseDate(),r.volumeName(),r.recommended());}).filter(Objects::nonNull).toList());}
 @GetMapping("/books/search") ApiResponse<List<ContentItem>> search(Authentication auth,@RequestParam String keyword){return ApiResponse.ok(items(books.findTop20ByTitleContainingIgnoreCaseOrAuthorContainingIgnoreCase(keyword,keyword),AuthSupport.userId(auth)));}
 @GetMapping("/books/{id}") ApiResponse<BookDetail> detail(Authentication auth,@PathVariable String id){Book b=book(id);return ApiResponse.ok(new BookDetail(b.getId(),b.getTitle(),b.getAuthor(),b.getPublisher(),b.getRating(),List.copyOf(b.getTags()),b.getDescription(),library.existsByUserIdAndBookId(AuthSupport.userId(auth),id)));}
 @GetMapping(value="/books/{id}/content.txt",produces="text/plain;charset=UTF-8") String content(@PathVariable String id){Book b=book(id);return b.getTitle()+"\n\n作者："+b.getAuthor()+"\n出版社："+b.getPublisher()+"\n\n"+b.getDescription()+"\n\n这是开发环境提供的示例阅读内容。正式内容可替换为对象存储中的 EPUB/TXT 文件。";}
 @GetMapping("/library") ApiResponse<List<LibraryItem>> library(Authentication auth){UUID me=AuthSupport.userId(auth);return ApiResponse.ok(library.findByUserIdOrderByCollectedAtDesc(me).stream().map(x->toLibrary(x,book(x.getBookId()))).toList());}
 @PostMapping("/library/{bookId}") @Transactional ApiResponse<LibraryItem> add(Authentication auth,@PathVariable String bookId){UUID me=AuthSupport.userId(auth);Book b=book(bookId);UserLibraryBook item=library.findByUserIdAndBookId(me,bookId).orElseGet(()->library.save(new UserLibraryBook(me,bookId)));return ApiResponse.ok(toLibrary(item,b));}
 @PutMapping("/library/{bookId}/progress") @Transactional ApiResponse<Void> progress(Authentication auth,@PathVariable String bookId,@RequestBody ProgressRequest r){UserLibraryBook item=library.findByUserIdAndBookId(AuthSupport.userId(auth),bookId).orElseThrow(()->new BusinessException(404,"书架中没有该书"));item.setProgress(r.progress());return ApiResponse.ok();}
 @DeleteMapping("/library/{bookId}") @Transactional ApiResponse<Void> remove(Authentication auth,@PathVariable String bookId){library.deleteByUserIdAndBookId(AuthSupport.userId(auth),bookId);return ApiResponse.ok();}
 private Book book(String id){return books.findById(id).orElseThrow(()->new BusinessException(404,"图书不存在"));} private List<ContentItem> items(List<Book> source,UUID user){return source.stream().map(b->item(b,user)).toList();} private ContentItem item(Book b,UUID user){return new ContentItem(b.getId(),b.getTitle(),b.getAuthor(),b.getPublisher(),b.getRating(),List.copyOf(b.getTags()),b.getDescription(),library.existsByUserIdAndBookId(user,b.getId()));}
 private LibraryItem toLibrary(UserLibraryBook x,Book b){String contentPath="/books/"+b.getId()+"/content.txt";return new LibraryItem(b.getId(),b.getTitle(),b.getAuthor()+" · "+b.getPublisher(),b.getRating(),List.copyOf(b.getTags()),"TXT",DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").format(x.getCollectedAt().atZone(ZoneId.systemDefault())),contentPath,x.getProgress());}
 private record PublishedRelease(String bookId,String releaseDate,String volumeName,boolean recommended){} private static final List<PublishedRelease> PUBLISHED_RELEASES=List.of(new PublishedRelease("fate-zero","2025-12-25","文库版 全三卷",false),new PublishedRelease("86","2026-08-07","Ep.14",true),new PublishedRelease("mahouka","2026-08-07","续篇 第3卷",false),new PublishedRelease("biblia","2026-08-10","第9卷",false),new PublishedRelease("spice-and-wolf","2026-08-10","Spring Log XI",true),new PublishedRelease("monogatari","2026-08-14","Off Season 05",false),new PublishedRelease("no-game-no-life","2026-08-14","第13卷",true),new PublishedRelease("bungo-stray-dogs","2026-09-01","STORM BRINGER 02",false),new PublishedRelease("danmachi","2026-09-15","第21卷",true),new PublishedRelease("sakurasou","2027-01-12","纪念版 第11卷",false));
 public record ContentItem(String id,String title,String author,String publisher,float rating,List<String> tags,String description,boolean isCollected){} public record RankingItem(int rank,ContentItem item){} public record NovelReleaseItem(ContentItem novel,String releaseDate,String volumeName,boolean isRecommended){} public record BookDetail(String id,String title,String author,String publisher,float rating,List<String> tags,String description,boolean isCollected){} public record LibraryItem(String id,String title,String subtitle,float rating,List<String> tags,String type,String collectedAt,String filePath,float progress){} public record ProgressRequest(@DecimalMin("0") @DecimalMax("1") float progress){}
}
