package com.sakuya.backend.friend;

import com.sakuya.backend.chat.ChatService; import com.sakuya.backend.common.*; import com.sakuya.backend.user.*; import com.sakuya.backend.notification.*;
import jakarta.validation.Valid; import jakarta.validation.constraints.NotNull; import jakarta.validation.constraints.Size;
import java.time.ZoneId; import java.time.format.DateTimeFormatter; import java.util.*;
import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/friends")
public class FriendController {
    private final FriendshipRepository friendships; private final FriendRequestRepository requests; private final UserRepository users; private final ChatService chat; private final NotificationService notificationService;
    public FriendController(FriendshipRepository friendships,FriendRequestRepository requests,UserRepository users,ChatService chat,NotificationService notificationService){this.friendships=friendships;this.requests=requests;this.users=users;this.chat=chat;this.notificationService=notificationService;}
    @GetMapping ApiResponse<List<FriendDto>> list(Authentication auth){UUID me=AuthSupport.userId(auth);return ApiResponse.ok(friendships.findByUserId(me).stream().map(Friendship::getFriendId).map(users::findById).flatMap(Optional::stream).map(FriendDto::from).toList());}
    @GetMapping("/search") ApiResponse<List<FriendDto>> search(Authentication auth,@RequestParam String keyword){UUID me=AuthSupport.userId(auth);String q=keyword.trim();if(q.isEmpty())return ApiResponse.ok(List.of());return ApiResponse.ok(users.findTop20ByNicknameContainingIgnoreCaseOrAccountContainingIgnoreCase(q,q).stream().filter(u->!u.getId().equals(me)).map(FriendDto::from).toList());}
    @PostMapping("/requests") @Transactional ApiResponse<Void> send(Authentication auth,@Valid @RequestBody FriendRequestDto dto){UUID me=AuthSupport.userId(auth);if(me.equals(dto.userId()))throw new BusinessException(400,"不能添加自己为好友");User target=users.findById(dto.userId()).orElseThrow(()->new BusinessException(404,"用户不存在"));if(!target.isCanBeAddedByStrangers())throw new BusinessException(400,"对方不允许陌生人添加");if(friendships.existsByUserIdAndFriendId(me,target.getId()))throw new BusinessException(400,"对方已经是你的好友");if(requests.existsBySenderIdAndReceiverIdAndStatus(me,target.getId(),FriendRequest.Status.PENDING))throw new BusinessException(400,"好友申请已发送");FriendRequest saved=requests.save(new FriendRequest(me,target.getId(),dto.message()));notificationService.create(target.getId(),me,AppNotification.Type.FRIEND_REQUEST,AppNotification.TargetType.FRIEND_REQUEST,saved.getId().toString(),me,saved.getId().toString());return ApiResponse.ok();}
    @GetMapping("/requests") ApiResponse<List<FriendRequestItem>> requests(Authentication auth){return ApiResponse.ok(requests.findByReceiverIdAndStatusOrderByCreatedAtDesc(AuthSupport.userId(auth),FriendRequest.Status.PENDING).stream().map(r->{User sender=users.findById(r.getSenderId()).orElseThrow();return FriendRequestItem.from(r,sender);}).toList());}
    @PutMapping("/requests/{id}/accept") @Transactional ApiResponse<FriendDto> accept(Authentication auth,@PathVariable UUID id){UUID me=AuthSupport.userId(auth);FriendRequest r=owned(id,me);r.accept();if(!friendships.existsByUserIdAndFriendId(me,r.getSenderId()))friendships.save(new Friendship(me,r.getSenderId()));if(!friendships.existsByUserIdAndFriendId(r.getSenderId(),me))friendships.save(new Friendship(r.getSenderId(),me));notificationService.create(r.getSenderId(),me,AppNotification.Type.FRIEND_ACCEPTED,AppNotification.TargetType.USER,me.toString(),me,r.getId().toString());return ApiResponse.ok(FriendDto.from(users.findById(r.getSenderId()).orElseThrow()));}
    @PutMapping("/requests/{id}/reject") @Transactional ApiResponse<Void> reject(Authentication auth,@PathVariable UUID id){owned(id,AuthSupport.userId(auth)).reject();return ApiResponse.ok();}
    @DeleteMapping("/{id}") @Transactional ApiResponse<Void> remove(Authentication auth,@PathVariable UUID id){UUID me=AuthSupport.userId(auth);friendships.deleteByUserIdAndFriendId(me,id);friendships.deleteByUserIdAndFriendId(id,me);return ApiResponse.ok();}
    @PostMapping("/{id}/conversation") ApiResponse<DirectConversationDto> conversation(Authentication auth,@PathVariable UUID id){UUID me=AuthSupport.userId(auth);if(!friendships.existsByUserIdAndFriendId(me,id))throw new BusinessException(403,"只能和好友创建单聊");var value=chat.direct(me,id);return ApiResponse.ok(new DirectConversationDto(value.id(),value.title()));}
    private FriendRequest owned(UUID id,UUID me){FriendRequest r=requests.findById(id).orElseThrow(()->new BusinessException(404,"好友申请不存在"));if(!r.getReceiverId().equals(me)||r.getStatus()!=FriendRequest.Status.PENDING)throw new BusinessException(400,"好友申请无法处理");return r;}
    public record FriendRequestDto(@NotNull UUID userId,@Size(max=200) String message){}
    public record DirectConversationDto(String id,String title){}
    public record FriendDto(String id,String name,String status,String avatarText,boolean isOnline,String avatarUrl){static FriendDto from(User u){String name=u.getNickname();return new FriendDto(u.getId().toString(),name,u.getSignature()==null?"":u.getSignature(),name.isBlank()?"":name.substring(0,1),false,u.getAvatarUrl());}}
    public record FriendRequestItem(String id,String userId,String name,String avatarText,String message,String createdAt){static FriendRequestItem from(FriendRequest r,User u){String n=u.getNickname();String time=DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(r.getCreatedAt().atZone(ZoneId.systemDefault()));return new FriendRequestItem(r.getId().toString(),u.getId().toString(),n,n.isBlank()?"":n.substring(0,1),r.getMessage(),time);}}
}
