pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://jitpack.io'}
        google()
        mavenCentral()

        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://github.com/psiegman/mvn-repo/raw/master/releases' }
        google()
        mavenCentral()

    }
}

rootProject.name = "sakuyainandroid"
include ':app'
include ':core:data'
include ':core:ui'
include ':core:common'
include ':core:di'
include ':core:model'
include ':core:navigation'

include ':feature:profile'
include ':feature:profile-services'
include ':feature:settings'
include ':feature:conversation'
include ':feature:friend'
include ':feature:authentication'
include ':core:designsystem'
include ':feature:home'
include ':feature:library'
include ':feature:reader'
