package com.sakuya.backend.chat;

import com.sakuya.backend.common.BusinessException; import com.sakuya.backend.user.*;
import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;
import org.springframework.data.domain.PageRequest; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class ChatService {
 private final ConversationRepository conversations; private final ConversationMemberRepository members; private final ChatMessageRepository messages; private final UserRepository users;
 public ChatService(ConversationRepository conversations,ConversationMemberRepository members,ChatMessageRepository messages,UserRepository users){this.conversations=conversations;this.members=members;this.messages=messages;this.users=users;}
 public List<ConversationDto> conversations(UUID userId){return members.findByUserId(userId).stream().map(m->toConversationDto(m,userId)).toList();}
 @Transactional public List<ChatMessageDto> messages(UUID userId,UUID conversationId,Long before,int limit){ConversationMember member=requireMember(userId,conversationId);var page=PageRequest.of(0,Math.max(1,Math.min(limit,100)));List<ChatMessage> found=before==null?messages.findByConversationIdOrderByCreatedAtDesc(conversationId,page):messages.findByConversationIdAndCreatedAtBeforeOrderByCreatedAtDesc(conversationId,Instant.ofEpochMilli(before),page);member.markRead();return found.reversed().stream().map(m->toDto(m,userId)).toList();}
 @Transactional public ChatMessage save(UUID userId,UUID conversationId,String content,String type){requireMember(userId,conversationId);if(content==null||content.isBlank())throw new BusinessException(400,"消息内容不能为空");if(content.length()>4000)throw new BusinessException(400,"消息内容过长");return messages.save(new ChatMessage(conversationId,userId,content,type==null?"text":type));}
 public ChatMessageDto toDto(ChatMessage m,UUID viewer){User sender=users.findById(m.getSenderId()).orElse(null);String name=sender==null?"":sender.getNickname();return new ChatMessageDto(m.getId().toString(),m.getConversationId().toString(),m.getContent(),label(m.getCreatedAt()),m.getSenderId().equals(viewer),avatar(name),m.getCreatedAt().toEpochMilli(),m.getMessageType());}
 public List<UUID> memberIds(UUID conversationId){return members.findByConversationId(conversationId).stream().map(ConversationMember::getUserId).toList();}
 @Transactional public Conversation create(String title,List<UUID> userIds){if(userIds.size()<2)throw new BusinessException(400,"会话至少需要两名成员");Conversation c=conversations.save(new Conversation(title));userIds.stream().distinct().forEach(id->members.save(new ConversationMember(c.getId(),id)));return c;}
 @Transactional public ConversationDto direct(UUID userId,UUID targetId){if(userId.equals(targetId))throw new BusinessException(400,"不能和自己创建单聊");User target=users.findById(targetId).orElseThrow(()->new BusinessException(404,"用户不存在"));for(ConversationMember membership:members.findByUserId(userId)){List<ConversationMember> all=members.findByConversationId(membership.getConversationId());if(all.size()==2&&all.stream().anyMatch(x->x.getUserId().equals(targetId)))return toConversationDto(membership,userId);}Conversation created=create(target.getNickname(),List.of(userId,targetId));return toConversationDto(members.findByConversationIdAndUserId(created.getId(),userId).orElseThrow(),userId);}
 @Transactional public void markRead(UUID userId,UUID conversationId){requireMember(userId,conversationId).markRead();}
 private ConversationDto toConversationDto(ConversationMember m,UUID viewer){Conversation c=conversations.findById(m.getConversationId()).orElseThrow();List<ConversationMember> all=members.findByConversationId(c.getId());String title=all.size()==2?all.stream().map(ConversationMember::getUserId).filter(id->!id.equals(viewer)).findFirst().flatMap(users::findById).map(User::getNickname).orElse(c.getTitle()):c.getTitle();Optional<ChatMessage> last=messages.findTopByConversationIdOrderByCreatedAtDesc(c.getId());long unread=messages.countByConversationIdAndCreatedAtAfterAndSenderIdNot(c.getId(),Instant.ofEpochMilli(m.getLastReadAt()),viewer);return new ConversationDto(c.getId().toString(),title,last.map(ChatMessage::getContent).orElse(""),last.map(x->label(x.getCreatedAt())).orElse(""),(int)Math.min(unread,Integer.MAX_VALUE),avatar(title),m.isPinned());}
 private ConversationMember requireMember(UUID user,UUID conversation){return members.findByConversationIdAndUserId(conversation,user).orElseThrow(()->new BusinessException(403,"你不在该会话中"));}
 private static String label(Instant time){return DateTimeFormatter.ofPattern("MM-dd HH:mm").withZone(ZoneId.systemDefault()).format(time);} private static String avatar(String s){return s==null||s.isBlank()?"":s.substring(0,1);}
 public record ConversationDto(String id,String title,String lastMessage,String timeLabel,int unreadCount,String avatarText,boolean isPinned){}
 public record ChatMessageDto(String id,String conversationId,String content,String timeLabel,boolean isMine,String avatarText,long timeStamp,String messageType){}
}
