package com.sakuya.backend.chat;
import com.fasterxml.jackson.databind.*; import java.util.*; import java.util.concurrent.ConcurrentHashMap; import org.springframework.stereotype.Component; import org.springframework.web.socket.*; import org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator; import org.springframework.web.socket.handler.TextWebSocketHandler;
@Component
public class ChatWebSocketHandler extends TextWebSocketHandler {
 private final ChatService chat; private final ObjectMapper json; private final Map<UUID,Map<String,WebSocketSession>> sessions=new ConcurrentHashMap<>();
 public ChatWebSocketHandler(ChatService chat,ObjectMapper json){this.chat=chat;this.json=json;}
 @Override public void afterConnectionEstablished(WebSocketSession session){UUID user=user(session);WebSocketSession safe=new ConcurrentWebSocketSessionDecorator(session,10_000,1024*1024);sessions.computeIfAbsent(user,x->new ConcurrentHashMap<>()).put(session.getId(),safe);}
 /** WebSocket 与 REST 使用同一附件 ID/回复协议和 ChatService 校验边界。 */
 @Override protected void handleTextMessage(WebSocketSession session,TextMessage text) throws Exception {try{UUID sender=user(session);JsonNode root=json.readTree(text.getPayload());if(!"message".equals(root.path("type").asText()))return;UUID conversation=UUID.fromString(root.path("conversationId").asText());JsonNode data=root.path("data");List<UUID>attachmentIds=new ArrayList<>();data.path("attachmentIds").forEach(node->attachmentIds.add(UUID.fromString(node.asText())));UUID replyTo=data.path("replyToMessageId").isTextual()?UUID.fromString(data.path("replyToMessageId").asText()):null;String clientMessageId=data.path("clientMessageId").isTextual()?data.path("clientMessageId").asText():null;ChatMessage saved=chat.save(sender,conversation,data.path("content").asText(""),data.path("messageType").asText("text"),attachmentIds,replyTo,clientMessageId);for(UUID member:chat.memberIds(conversation)){var payload=Map.of("type","message","conversationId",conversation.toString(),"data",chat.toDto(saved,member));String body=json.writeValueAsString(payload);for(WebSocketSession target:sessions.getOrDefault(member,Map.of()).values())if(target.isOpen())target.sendMessage(new TextMessage(body));}}catch(Exception e){session.sendMessage(new TextMessage(json.writeValueAsString(Map.of("type","error","message",e.getMessage()==null?"消息处理失败":e.getMessage()))));}}
 @Override public void afterConnectionClosed(WebSocketSession session,CloseStatus status){remove(session);}
 @Override public void handleTransportError(WebSocketSession session,Throwable exception){remove(session);}
 private void remove(WebSocketSession session){UUID user=user(session);Map<String,WebSocketSession> userSessions=sessions.get(user);if(userSessions!=null){userSessions.remove(session.getId());if(userSessions.isEmpty())sessions.remove(user);}}
 private UUID user(WebSocketSession s){return (UUID)s.getAttributes().get("userId");}
}
